In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s3e25/sample_submission.csv
/kaggle/input/playground-series-s3e25/train.csv
/kaggle/input/playground-series-s3e25/test.csv


In [2]:
train_data = pd.read_csv('/kaggle/input/playground-series-s3e25/train.csv')
train_data

id  allelectrons_Total  density_Total  allelectrons_Average  \
0          0               100.0       0.841611             10.000000   
1          1               100.0       7.558488             10.000000   
2          2                76.0       8.885992             15.600000   
3          3               100.0       8.795296             10.000000   
4          4               116.0       9.577996             11.600000   
...      ...                 ...            ...                   ...   
10402  10402               128.0       7.558488             12.000000   
10403  10403                30.0       1.743160             10.000000   
10404  10404               196.0      30.920000             24.500000   
10405  10405                38.0       1.553160             12.666667   
10406  10406               288.0      24.655328             11.142857   

       val_e_Average  atomicweight_Average  ionenergy_Average  \
0           4.800000             20.612526          11.088100   
1           4.800000             20.298893          12.040830   
2           5.600000             33.739258          12.086300   
3           4.800000             20.213349          10.948500   
4           4.800000             24.988133          11.824480   
...              ...                   ...                ...   
10402       4.000000             26.385218          11.330440   
10403       5.333333             20.766935          14.163933   
10404       5.500000             53.490297          10.074300   
10405       4.666667             26.621687          11.290033   
10406       4.571429             22.536126          10.960357   

       el_neg_chi_Average  R_vdw_element_Average  R_cov_element_Average  \
0                2.766000               1.732000               0.860000   
1                2.755000               1.631000               0.910000   
2                2.828000               1.788000               0.864000   
3                2.648000               1.626000               0.936000   
4                2.766000               1.682000               0.896000   
...                   ...                    ...                    ...   
10402            2.644000               1.631000               0.892000   
10403            3.090000               1.556667               0.866667   
10404            2.295000               1.545000               1.120000   
10405            2.743333               1.756667               0.980000   
10406            2.792143               1.772857               0.940000   

       zaratio_Average  density_Average  Hardness  
0             0.496070          0.91457       6.0  
1             0.492719          0.71760       6.5  
2             0.481478          1.50633       2.5  
3             0.489272          0.78937       6.0  
4             0.492736          1.86481       6.0  
...                ...              ...       ...  
10402         0.496070          1.79607       4.0  
10403         0.480390          0.81480       5.0  
10404         0.469715          2.11540       1.8  
10405         0.486507          0.77755       6.0  
10406         0.493919          0.97737       6.5  

[10407 rows x 13 columns]

In [3]:
test_data = pd.read_csv('/kaggle/input/playground-series-s3e25/test.csv')
test_data


id  allelectrons_Total  density_Total  allelectrons_Average  \
0     10407               884.0     121.420000             35.360000   
1     10408                90.0       9.931960             18.000000   
2     10409               116.0       7.767992             11.600000   
3     10410               100.0       9.107996             10.000000   
4     10411                55.0       4.030000             11.000000   
...     ...                 ...            ...                   ...   
6934  17341               446.0      36.135392              9.636364   
6935  17342                36.0       3.550000             18.000000   
6936  17343                68.0       4.545328             11.333333   
6937  17344                40.0       2.334164              6.666667   
6938  17345               134.0      17.590000             67.000000   

      val_e_Average  atomicweight_Average  ionenergy_Average  \
0          5.280000             82.561240           9.370384   
1          5.600000             39.568056          12.086300   
2          4.800000             23.231818          11.023840   
3          4.800000             20.298893          12.086300   
4          4.000000             22.977675          11.280950   
...             ...                   ...                ...   
6934       4.636364             19.689448          11.045515   
6935       4.000000             36.068500           8.236600   
6936       5.333333             22.688853          10.938358   
6937       4.000000             13.016128          12.700467   
6938       5.000000            167.400000           8.213150   

      el_neg_chi_Average  R_vdw_element_Average  R_cov_element_Average  \
0               2.298000               1.907200               1.200000   
1               2.868000               1.652000               0.864000   
2               2.644000               1.794000               0.960000   
3               2.828000               1.662000               0.792000   
4               2.455000               1.750000               0.893333   
...                  ...                    ...                    ...   
6934            2.768636               1.769697               0.871818   
6935            1.790000               2.055000               1.390000   
6936            2.876667               1.713333               0.916667   
6937            2.770000               1.476667               0.616667   
6938            1.950000               2.040000               1.410000   

      zaratio_Average  density_Average  
0            0.461899          1.79459  
1            0.476196          1.41194  
2            0.499514          0.78834  
3            0.495796          1.20466  
4            0.476095          0.93456  
...               ...              ...  
6934         0.498702          0.11548  
6935         0.499000          1.35045  
6936         0.499074          0.73425  
6937         0.663797          0.51227  
6938         0.401635          0.44035  

[6939 rows x 12 columns]

In [4]:
features_ = ['allelectrons_Total', 'density_Total', 'allelectrons_Average',
       'val_e_Average', 'atomicweight_Average', 'ionenergy_Average',
       'el_neg_chi_Average', 'R_vdw_element_Average', 'R_cov_element_Average',
       'zaratio_Average', 'density_Average']
x_train = np.array(train_data[features_])
x_test = np.array(test_data[features_])
x_train
x_test

array([[8.84000000e+02, 1.21420000e+02, 3.53600000e+01, ...,
        1.20000000e+00, 4.61899200e-01, 1.79459000e+00],
       [9.00000000e+01, 9.93196000e+00, 1.80000000e+01, ...,
        8.64000000e-01, 4.76196000e-01, 1.41194000e+00],
       [1.16000000e+02, 7.76799200e+00, 1.16000000e+01, ...,
        9.60000000e-01, 4.99514000e-01, 7.88340000e-01],
       ...,
       [6.80000000e+01, 4.54532800e+00, 1.13333333e+01, ...,
        9.16666667e-01, 4.99074167e-01, 7.34250000e-01],
       [4.00000000e+01, 2.33416350e+00, 6.66666667e+00, ...,
        6.16666667e-01, 6.63796667e-01, 5.12270000e-01],
       [1.34000000e+02, 1.75900000e+01, 6.70000000e+01, ...,
        1.41000000e+00, 4.01635000e-01, 4.40350000e-01]])

In [5]:
y_train = np.array(train_data['Hardness'])
y_train

array([6. , 6.5, 2.5, ..., 1.8, 6. , 6.5])

In [6]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train,y_train)
predictions = model.predict(x_test)
predictions

array([3.47755869, 4.83643179, 5.28395533, ..., 5.46043265, 4.34650171,
       1.67574438])

In [7]:
df = pd.DataFrame({'id':test_data['id'],'Hardness':predictions})
df

id  Hardness
0     10407  3.477559
1     10408  4.836432
2     10409  5.283955
3     10410  5.276157
4     10411  5.095199
...     ...       ...
6934  17341  5.501100
6935  17342  4.488108
6936  17343  5.460433
6937  17344  4.346502
6938  17345  1.675744

[6939 rows x 2 columns]

In [8]:
df.to_csv('submission.csv',index=True)